"""empty message

Revision ID: a6e696bad74d
Revises: a574991573aa
Create Date: 2020-09-17 19:04:02.465266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e696bad74d'
down_revision = 'a574991573aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salon', 'addresse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon', sa.Column('addresse', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
