"""empty message

Revision ID: f80324ea51cf
Revises: a6e696bad74d
Create Date: 2020-09-17 19:06:03.784305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80324ea51cf'
down_revision = 'a6e696bad74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salon', 'addresse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon', sa.Column('addresse', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
